"""added sms user fields

Revision ID: cc37cebfbf05
Revises: 36e303213dda
Create Date: 2020-12-07 19:49:21.228228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc37cebfbf05'
down_revision = '36e303213dda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('standard_decks', 'source',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.add_column('users', sa.Column('phone_number', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('sms_enabled', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_sms_enabled'), 'users', ['sms_enabled'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_sms_enabled'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_column('users', 'sms_enabled')
    op.drop_column('users', 'phone_number')
    op.alter_column('standard_decks', 'source',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###
